import { createApp, VueElement } from "vue";
import "./style.css";
import router from "./router/index";
import App from "./App.vue";
import { createPinia } from "pinia";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import "./assets/iconfont/iconfont.css";
import "./assets/base.css";
import loginInput from "./components/login/loginInput.vue";
import naive from "naive-ui";
import navBar from "./components/navBar/navBar.vue";
import send from "./components/forget/send.vue";
import complete from "./components/forget/complete.vue";
import reset from "./components/forget/reset.vue";
import forgetInput from "./components/forget/forgetInput.vue";
import next from "./components/forget/next.vue";
const app = createApp(App);
const pinia = createPinia();
app.component("loginInput", loginInput);
app.component("send", send);
app.component("complete", complete);
app.component("reset", reset);
app.component("next", next);
app.component("navBar", navBar);
app.component("forgetInput", forgetInput);
app.use(pinia);
app.use(naive);
app.use(ElementPlus);
app.use(router).mount("#app");
